version: '3'
services:
  eureka:
    image: eurekaserver
    ports: 
    - "8761:8761"
  compute:
    image: compute
    ports: 
    - "8100:8100"
    depends_on:
    - eureka
  compute1:
    image: compute
    ports: 
    - "8101:8100"
    depends_on:
    - eureka
  compute2:
    image: compute
    ports: 
    - "8102:8100"
    depends_on:
    - eureka
  quotation:
    image: compute
    ports: 
    - "8200:8200"
    depends_on:
    - eureka
